#!/bin/bash

echo "Running pre-push checks..."
echo "Running \`cargo fmt\` on each crate..."
cargo fmt -- --check > /dev/null
RUSTFMT_EXIT_CODE=$?

if [[ $RUSTFMT_EXIT_CODE = 0 ]]; then
  echo "Project passes \`cargo fmt\`!"
else
  echo "Project isn't formatted correctly. Run \`cargo fmt\` please!"
  exit 1
fi

echo "Running \`cargo clippy\`..."
CLIPPY_ERR=$(cargo clippy --all-targets --all-features -- -D warnings 2>&1)
if [[ $CLIPPY_ERR =~ "error" ]]; then
  echo "Project is uggo. Run \`cargo clippy --all-targets --all-features -- -D warnings\` and either fix or mute the errors please!."
  exit 1
else
  echo "Project is stylish!"
fi